### ISSUE TITLE
Erro também no adicionamento de cliente

### ISSUE THREAD

**Issue by Allanads** [Allanads/WebSite_Seguradora#4]
Erro também no adicionamento de cliente, pois os códigos do cliente esta indo de ao contrario, chegou no código "0" não deixa incluir mais nenhum fica dando erro ao adicionar mais algum cliente.

**Comment by Dev-Daniel-Santos** [comment]
@Allanads já tentou verificar todos os tipos relacionados aos inputs, pois podem estar dando conflito um com outros.
